import { Footer, Layout, Navbar } from 'nextra-theme-docs'
import { Head } from 'nextra/components'
import { getPageMap } from 'nextra/page-map'
import 'nextra-theme-docs/style.css'
import type { Metadata } from 'next'

const SITE_URL = 'https://docs.remoet.dev'
const DEFAULT_TITLE = 'remoet.dev developer documentation'
const DEFAULT_DESCRIPTION =
  'Connect AI agents to your remoet.dev data via MCP, or fetch your profile programmatically via the REST API.'

// The OG image is generated by app/opengraph-image.tsx — Next auto-injects
// the og:image / twitter:image tags pointing at it, so we don't set them
// in this static metadata block.
export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    template: '%s — remoet.dev docs',
    default: DEFAULT_TITLE,
  },
  description: DEFAULT_DESCRIPTION,
  openGraph: {
    title: DEFAULT_TITLE,
    description: DEFAULT_DESCRIPTION,
    url: SITE_URL,
    siteName: 'remoet.dev docs',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    site: '@remoet_dev',
    title: DEFAULT_TITLE,
    description: DEFAULT_DESCRIPTION,
  },
  alternates: {
    canonical: SITE_URL,
  },
  robots: {
    index: true,
    follow: true,
  },
}

const websiteJsonLd = {
  '@context': 'https://schema.org',
  '@type': 'WebSite',
  name: 'remoet.dev developer documentation',
  url: SITE_URL,
  publisher: {
    '@type': 'Organization',
    name: 'remoet.dev',
    url: 'https://www.remoet.dev',
  },
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const navbar = (
    <Navbar
      logo={<span>remoet.dev</span>}
      projectLink="https://github.com/remoet-labs/remoet-docs"
      chatLink="https://discord.gg/yxJA6cBs8U"
    />
  )
  const pageMap = await getPageMap()
  return (
    <html lang="en" dir="ltr" suppressHydrationWarning>
      <Head />
      <body>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(websiteJsonLd) }}
        />
        <Layout
          navbar={navbar}
          footer={<Footer>remoet.dev © 2026</Footer>}
          docsRepositoryBase="https://github.com/remoet-labs/remoet-docs"
          pageMap={pageMap}
        >
          {children}
        </Layout>
      </body>
    </html>
  )
}
